# 廢土對賭機器人設定檔
# 1. 每個設定的選項後面都有說明，請詳閱
# 2. 若出現 "" ，請在兩個雙引號內填入適當的文字，並請勿刪除雙引號
# 3. 若出現 [] ，且您僅有一項參數要填，請填 ["你的參數"]
# 4. 若出現 [] ，且您有兩項參數要填，請填 ["你的參數 1", "你的參數 2"] 
# 5. 若出現 [] ，且您有三項參數要填，請填 ["你的參數 1", "你的參數 2", "你的參數 3"] ，若更多參數則以此類推

# 必填區域
[general]
whitelist = ["Jimmy4Real"] # 伺服器白名單玩家的 Minecraft ID，當機器人偵測到下注玩家不在白名單內時將不予接受下注，請填入 Minecraft ID 而非 UUID

[discord]
discordBotToken = "" # Discord Bot 的 token，可至 Discord 開法者頁面取得
discordApplicationID = "" # Discord Bot 的 application id，可至 Discord 開法者頁面取得

[[bots]]
username = "" # Bot 的代號，不一定要填實際的 Minecraft ID 或是電子郵件，僅能填英文和數字
uuid = "" # Bot 的 Minecraft UUID (請移除 "-")
serverIP = "mcfallout.net" # 伺服器 IP，為了避免伺服器卡頓而造成 Bot 無法使用，故新增了此項設定
whitelist = ["Jimmy4Real"] # 白名單的 Minecraft 玩家的 ID
betRecordChannelID = "" # 下注紀錄的 Discord 頻道 ID
consoleChannelID = "" # Console 的 Discord 頻道 ID
# 以下可不填，若不填則會使用預設值，可透過 discord 指令修改
emax = 5000000 
emin = 1
cmax = 5000000
cmin = 1
eodds = 1.85
codds = 1.85

# 自動宣傳訊息 (可設定多則，會依序循環發送)
[[bots.autoMessages]]
message = "test1"
waitSeconds = 300

[[bots.autoMessages]]
message = "test2"
waitSeconds = 600